[package]
name = "motiongfx"
description = "Backend agnostic motion graphics creation tool."
exclude = ["/assets/", "/.github/", "/examples/"]
keywords = ["motion", "animation", "procedural", "bevy"]
categories = ["multimedia", "graphics", "gui", "rendering", "game-development", "no_std"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# bevy
bevy_ecs = { workspace = true }
bevy_platform = { workspace = true }
bevy_math = { workspace = true }

# other
field_path = { workspace = true }
nonempty = { workspace = true }

[lints]
workspace = true
