[package]
name = "motiongfx_engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy = { workspace = true, features = ["animation", "bevy_asset", "bevy_log"] }
smallvec = { workspace = true }
nonempty = "0.11.0"

[lints]
workspace = true

[features]
default = ["asset"]
asset = []
